video_new:
    path:   /new
    defaults: { _controller: "AppBundle:Video:new"}
    methods: POST

video_edit:
    path:   /edit/{id}
    defaults: { _controller: "AppBundle:Video:edit", id:null}
    methods: POST