app_default: 
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix: /

app_user: 
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user

app_video: 
    resource: "@AppBundle/Resources/config/routing/video.yml"
    prefix: /video